//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forest.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForestDatabaseEntities : DbContext
    {
        public ForestDatabaseEntities()
            : base("name=ForestDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Music_Catergory> Music_Catergory { get; set; }
        public virtual DbSet<Music_Recording> Music_Recording { get; set; }

        public System.Data.Entity.DbSet<Forest.Data.BEANS.MusicBEAN> MusicBEANs { get; set; }
    }
}
